### ISSUE TITLE
issue with the rendering of the custom font

### ISSUE THREAD

**Issue by BletaJonatan** [ChrisTitusTech/powershell-profile#101]
Hello everybody i'm currently on:
 WIN10 64 bit last version
 Powershell 7.4.4
 
 i cant seem to be able to render the text correctly after installing the profile:
 ~ 
~ 
~  cd .\Desktop\
~\Desktop 
![immagine](https://github.com/user-attachments/assets/c21f2a6b-0ecb-4390-87de-cab00d22d2c5)

now one more thing is that the profile errored out since i already had chocolatey so i deleted the folder and the script seemed to go without issue, problem is the script itself has issues if it finds the same chocolatey installation the script itself installed 5 minutes ago instead of skipping it.

**Comment by BletaJonatan** [comment]
i do understand that ohmyposh says:
To ensure correct rendering of the glyphs you will need to enable the option Use the new text renderer ("AtlasEngine") in your terminal settings. For further details, see [here](https://github.com/microsoft/terminal/issues/8993).
but it gives the same thing on the terminal app as well.

**Comment by v-amorim** [comment]
@BletaJonatan 
Are you using Powershell or Windows Terminal?

Both you need to set the default font, and it need to be a Nerd Font to be able to see icons

**Comment by BletaJonatan** [comment]
the 0xproto nerd font is installed and selected, the edit profile function was not used.

**Comment by BletaJonatan** [comment]
i've understood that i needed to reapply the theme as well in the profile ps1, my bad.
