### ISSUE TITLE
issues after one line install

### ISSUE THREAD

**Issue by lmcr666** [ChrisTitusTech/powershell-profile#116]
Tried one line install and now i get a whole bunch of errors when opening powershell and when reloading profile.
Powershell still looks mostly the same.
![image](https://github.com/user-attachments/assets/5747425c-4126-43bb-baa8-feabfc91391b)

Thank you in advance for helping.
Sorry im trying to get into using powershell and vim more often and its not going so well thus far ahah.

**Comment by mrsph1nx** [comment]
test-connection is not  [Windows PowerShell] (v5.1) command. 
It is a PWSH (PowerShell v.7+) command
the v.5 equivalent is test-netconnection (which doesnt have the parameter -count inside)

If you want to install the PWSH in your VSCODE:
https://code.visualstudio.com/docs/languages/powershell

**Comment by mrsph1nx** [comment]
@ChrisTitusTech you might want to modify your code to be cross version compliant with **_test-netconnection_** command instead

**Comment by lmcr666** [comment]
ye, i updated to powershell 7.4 and its working now :)
