### ISSUE TITLE
Theme broke randomly. 

### ISSUE THREAD

**Issue by RambonL** [ChrisTitusTech/powershell-profile#119]
Hello everyone,

I've encountered an issue with my PowerShell profile. Up until recently, it worked perfectly with the standard powershell-profile theme.

In the first image, you can see my profile configuration: 
![image](https://github.com/user-attachments/assets/375c2774-6de1-4aec-916a-5ac56a15867c)

However, this is what my profile currently looks like: 
![image](https://github.com/user-attachments/assets/449995a1-05bc-4258-8e3d-fbfa8a6c0ee6)

As shown, the theme has unexpectedly changed from the standard powershell-profile look. This happened randomly after a regular PC startup. Additionally, the profile now takes around 20 seconds to load, which is significantly slower than before.

Any help in diagnosing or fixing this issue would be greatly appreciated. Thank you!

**Comment by RambonL** [comment]
Yes I did the update. Thank you for the info

**Comment by baxlash** [comment]
I have the same issue. As soon as the profile.ps1 is created (no matter if it is empty or any personal settings are put there) the prompt theme is not applied anymore.
As a workaround I invoked it from inside the profile.ps1 file and so it is applied.

**Comment by baxlash** [comment]
I put this line inside the profile.ps1 (the file with the personal settings):

`oh-my-posh init pwsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/cobalt2.omp.json | Invoke-Expression
`

**Comment by RambonL** [comment]
> I put this line inside the profile.ps1 (the file with the personal settings):
> 
> `oh-my-posh init pwsh --config https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/cobalt2.omp.json | Invoke-Expression `

Ty. I have something really similar (e.g. first screenshot). I dont know why this isnt working for me.

**Comment by RambonL** [comment]
I found the solution! The issue was related to my VPN. I use Mullvad VPN, and it turns out that every time I disable the VPN and then start PowerShell, everything runs smoothly without any issues. After that, I can turn the VPN back on, and everything continues to work perfectly.
