### ISSUE TITLE
Terminal Icons are not working properly

### ISSUE THREAD

**Issue by AssassinK786** [ChrisTitusTech/powershell-profile#14]
![powershell icons issue](https://user-images.githubusercontent.com/85348050/201470308-662043b6-35be-486f-827e-088081c9d632.JPG)
I'm getting this Icons issue

**Comment by omaru-ok** [comment]
your fonts are wrong , get from here  [nerd-font](https://www.nerdfonts.com/font-downloads)

**Comment by AssassinK786** [comment]
Ok i have got the fonts, what is next steps i need to do?

**Comment by jebbisson** [comment]
I had to manually set the fonts after installing them manually, not sure if that was the expected way to do this or not:
![image](https://user-images.githubusercontent.com/8978829/202050973-976c2793-12cd-4c53-84b5-1004c479188b.png)
I installed all 4 of them, again not sure if that was necessary.
![image](https://user-images.githubusercontent.com/8978829/202050826-5be6f480-17c2-46ff-90aa-7c38821b1bce.png)

**Comment by AssassinK786** [comment]
![image](https://user-images.githubusercontent.com/85348050/202502693-65161a49-a659-4df4-8649-395cc93d32a9.png)
It is Working @jebbisson @omaru-ok 
Thanks for Help!
