### ISSUE TITLE
Oh my Posh 

### ISSUE THREAD

**Issue by barony06** [ChrisTitusTech/powershell-profile#15]
how i change oh my posh theme? 
i tried go to powershell profile created in #documents folder and change the line oh-my-posh --init --shell pwsh --config ~/jandedobbeleer.omp.json | Invoke-Expression but it doesn't work
i tried tokyo and dracula themes, without sucess

**Comment by sahil-jindal** [comment]
You should checkout [ohmyposh.dev](url) for switching themes

**Comment by omaru-ok** [comment]
Hey, @barony06  im rather happy by usign [starship](https://starship.rs/) its very easy to use tho :)
