### ISSUE TITLE
Uninstall the profile and scripts

### ISSUE THREAD

**Issue by sameerasw** [ChrisTitusTech/powershell-profile#20]
I uninstalled Oh My Posh completely and re-installed but couldn't get back to default settings of oh-my-posh and change the theme according to the [guides](https://ohmyposh.dev/docs/installation/customize). Some help for a noob?

**Comment by sahil-jindal** [comment]
What were your default settings? Also, I would like to know some more information (if possible).

**Comment by sameerasw** [comment]
> Hi @sameerasw, What were your default settings? Also, I would like to know some more information (if possible).

I would like to know how to completely remove this script and it's affects. Because it takes quite a time for my pc to load.
I tried changing my Oh-My-Posh theme as the guides but it doesn't make any changes... I even completely re-created my powershell profile but just after I added oh-my-posh to the execution, It reverts back to the state which it was before... I couldn't find where these changes are located.

Can you give me a little help on reverting every change to it's default? Because it takes around 2 seconds to load the CLI and it's a bit annoying on day to day use.

![image](https://user-images.githubusercontent.com/68902530/212528190-a426b02d-a086-403d-89cf-4c91024f6672.png)

**Comment by sahil-jindal** [comment]
Based on the `setup.ps1` present in this repo, the script must be present in 
1) `C:\Users\<yourusername>\Documents\Powershell` if you installed using Powershell 7+.
2) `C:\Users\<yourusername>\Documents\WindowsPowerShell` if you installed using Windows Powershell.

There, you will find the file as `Microsoft.PowerShell_profile.ps1`.

Can simply delete this file to revert back to default look of Powershell.

**Comment by sameerasw** [comment]
> 

Thank you! Removing Chocolatey fixed... Now I'm able to set up everything as normal.
Now it doesn't take seconds to load profiles and instant.
![image](https://user-images.githubusercontent.com/68902530/212540382-8033a94e-a03a-4d04-be83-02af8526b0fe.png)
