### ISSUE TITLE
dose no funktion on macos

### ISSUE THREAD

**Issue by mcpeapsUnterstrichHD** [ChrisTitusTech/powershell-profile#21]
dose no funktion on macos

[comout1](https://app.warp.dev/block/oTOTKVkZ0DaHWjGXIijXPg)
[comout2](https://app.warp.dev/block/YXh9eXJtEogmLLYSfLA14g)

**Comment by omaru-ok** [comment]
@mcpeapsUnterstrichHD  it would be better if u update your powershell , and try then 

also the setup.s1 is intended  to be run on window filesystem . while macos uses linux like filesystem hierarchy  so 🤷 i think it may be not quite good idea for mac to use that configs
