### ISSUE TITLE
Terminal Icon for Folder not showing

### ISSUE THREAD

**Issue by mac-nv** [ChrisTitusTech/powershell-profile#25]
I ran the profile install command, set the Nerd Fonts, and found that the Folder icon (orange tab in the prompt) isn't showing properly.  Tried all the Nerd Fonts that download with the script.  Also tried this on two other computers I have (Win10 and Win11) and was able to replicate the issue.

![image](https://github.com/ChrisTitusTech/powershell-profile/assets/137470520/15dddc3e-8ce7-44b0-a9bd-ea6b03703f10)

![image](https://github.com/ChrisTitusTech/powershell-profile/assets/137470520/ac6484ba-1ac6-4597-84c4-ba0d4da6cdec)

**Comment by NormTurtle** [comment]
install the font this time with 
`install for all user` with admin right
then reboot, see the results

**Comment by mac-nv** [comment]
Hi @NormTurtle.  I tried that but unfortunately the issue is persistent.

**Comment by ChrisTitusTech** [comment]
Just had this exact thing happen to me and installing for all users DID FIX the issue. Good find! 
![image](https://github.com/ChrisTitusTech/powershell-profile/assets/7896101/e155c575-77d7-4896-a642-79a879a6514a)
