### ISSUE TITLE
Some icons are missing/broken

### ISSUE THREAD

**Issue by abdurrahmanseyidoglu** [ChrisTitusTech/powershell-profile#26]
I have installed the fonts for all users but there are some broken icons and I can't figure out how to fix them 
here is a screenshot to demonstrate 

![image](https://github.com/ChrisTitusTech/powershell-profile/assets/40239163/7aafb8c7-197d-48a9-8dc3-b4c716533194)

**Comment by NormTurtle** [comment]
try `reinstalling` font

**Comment by abdurrahmanseyidoglu** [comment]
> try `reinstalling` font

I did twice, but didn't work

**Comment by NormTurtle** [comment]
try different font https://github.com/adam7/delugia-code/releases
like this one

**Comment by abdurrahmanseyidoglu** [comment]
> try different font https://github.com/adam7/delugia-code/releases like this one
This font worked for me thanks!
