### ISSUE TITLE
Error zoxide

### ISSUE THREAD

**Issue by jok3rsgr1n** [ChrisTitusTech/powershell-profile#29]
PowerShell 7.3.7
zoxide: C:\Users\danzg\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:219
Line |
 219 |  Invoke-Expression (& { (zoxide init powershell | Out-String) })
     |                          ~~~~~~
     | The term 'zoxide' is not recognized as a name of a cmdlet, function, script file, or executable program. Check
     | the spelling of the name, or if a path was included, verify that the path is correct and try again.
Invoke-Expression: C:\Users\danzg\Documents\PowerShell\Microsoft.PowerShell_profile.ps1:219
Line |
 219 |  Invoke-Expression (& { (zoxide init powershell | Out-String) })
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Command' because it is null.

**Comment by crcastilho** [comment]
Just install it. winget install zoxide -s winget
