### ISSUE TITLE
vim editor config

### ISSUE THREAD

**Issue by rajorshi-mandal** [ChrisTitusTech/powershell-profile#4]
i am not sure if its only with my system but when i typed "vim" i am getting the following error
![Screenshot (1834)](https://user-images.githubusercontent.com/62472908/199045251-a3b3f268-fc92-44c4-884f-7f375d33d651.png)

**Comment by rajorshi-mandal** [comment]
> i am not sure if its only with my system but when i typed "vim" i am getting the following error ![Screenshot (1834)](https://user-images.githubusercontent.com/62472908/199045251-a3b3f268-fc92-44c4-884f-7f375d33d651.png)

its working in normal powershell but launching it will windows terminal doesnt seem to work does they have different commands for execution ?

**Comment by TheyCallMeZ** [comment]
In this block of Chris's Script he is checking to see what is installed on your system to determine which editor to use.
`if (Test-CommandExists nvim) {
    $EDITOR='nvim'
} elseif (Test-CommandExists pvim) {
    $EDITOR='pvim'
} elseif (Test-CommandExists vim) {
    $EDITOR='vim'
} elseif (Test-CommandExists vi) {
    $EDITOR='vi'
}
Set-Alias -Name vim -Value $EDITOR`

The options are Neovim
https://github.com/neovim/neovim/wiki/Installing-Neovim

(I can only assume pvim is parasitic vim, and it uses the nimble library)
https://github.com/paranim/pvim

vim
https://www.vim.org/download.php 
-or-
winget install vim.vim

vi
(I think you need to install cygwin to get this?)

So I think the best options would be to get neovim or vim installed.

**Comment by bertman80** [comment]
For all the EDITOR messages, just put this on line 133 just before the 'if (Test-CommandExists nvim) {'
So the editor will be notepad if none of the other commands exist.
`$EDITOR="notepad.exe"`

**Comment by itsRealGray** [comment]
> In this block of Chris's Script he is checking to see what is installed on your system to determine which editor to use. `if (Test-CommandExists nvim) { $EDITOR='nvim' } elseif (Test-CommandExists pvim) { $EDITOR='pvim' } elseif (Test-CommandExists vim) { $EDITOR='vim' } elseif (Test-CommandExists vi) { $EDITOR='vi' } Set-Alias -Name vim -Value $EDITOR`
> 
> The options are Neovim https://github.com/neovim/neovim/wiki/Installing-Neovim
> 
> (I can only assume pvim is parasitic vim, and it uses the nimble library) https://github.com/paranim/pvim
> 
> vim https://www.vim.org/download.php -or- winget install vim.vim
> 
> vi (I think you need to install cygwin to get this?)
> 
> So I think the best options would be to get neovim or vim installed.

**Thanks** @TheyCallMeZ i had same issue #19 and as you recomended 'neovim or vim' could resolve that problem and i did 'choco install neovim' and Wallah its worked!

heres the SS 
![Annotation 2023-01-19 030346](https://user-images.githubusercontent.com/102512869/213299824-da576e82-a39b-4c78-91ee-ce2757ce4fec.png)

**Comment by ChrisTitusTech** [comment]
Took @TheyCallMeZ snippit to expand the editors to fix this issue in commit 7381f33
