### ISSUE TITLE
idk why it show me this when i launch ps + my push font doesn't work at all

### ISSUE THREAD

**Issue by HolakoNoob** [ChrisTitusTech/powershell-profile#5]
At C:\Users\Administrator\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:125 char:25
+ if (( $+commands[nvim] )); then
+                         ~
Missing statement block after if ( condition ).
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingStatementBlock

![2](https://user-images.githubusercontent.com/70993209/199052149-5aae6d91-becd-42e5-a30f-67ec8572c681.png)
![1](https://user-images.githubusercontent.com/70993209/199052180-c79fb448-2b94-4d5f-98be-438240ae6112.png)

**Comment by TheyCallMeZ** [comment]
@HolakoNoob Chris has since updated his script, please re-pull it and try again.
