### ISSUE TITLE
A parameter cannot be found that matches parameter name 'TimeoutSeconds'.

### ISSUE THREAD

**Issue by Ramy-Ashraf** [ChrisTitusTech/powershell-profile#51]
I get this error every time I open powershell
![image](https://github.com/ChrisTitusTech/powershell-profile/assets/85342902/4840d221-725e-4dce-9cb5-03f058513a89)

**Comment by dusberendguy** [comment]
Hi, this was closed. I have this problem, what is the solution?

**Comment by Ramy-Ashraf** [comment]
The solution for any one looking is to download PowerShell 7. This problem exists only in PowerShell 5.1.
