### ISSUE TITLE
Suggestion about Oh-My-Posh config change 

### ISSUE THREAD

**Issue by xicor22** [ChrisTitusTech/powershell-profile#52]
Hi, I have feature request regarding the Oh-My-Posh config.
It'd be nice to have a environment variable to change the OMP config so that it's easy to change it's config file as the script goes back to the default theme after checking the hash at startup.

P.S. I have been watching your channel since 2022 and I just wanna say thank you for your scripts and tools.

**Comment by suppeppo** [comment]
I made a pull request that should alleviate this issue, in allowing for custom themes to be loaded from Profile.ps1 #68
