### ISSUE TITLE
edit-profile does not point to $profile

### ISSUE THREAD

**Issue by mickleby** [ChrisTitusTech/powershell-profile#54]
edit-profile wants to create profile.ps1 rather than edit microsoft.powershell_profile.ps1

**Comment by boubakeraddy** [comment]
same here

**Comment by suppeppo** [comment]
As stated in setup.ps1:

>If you want to add any persistent components, please do so at [$profilePath\Profile.ps1] as there is an updater in the installed profile which uses the hash to update the profile and will lead to loss of changes

So it seems to be working as intended.

**Comment by natep-tech** [comment]
For more context, the profile provided in this repo is for all users. By using the Edit-Profile function, you create a separate profile for the current user, where new functions can be defined without interfering with the main profile.
