### ISSUE TITLE
How to add Terminal icons?

### ISSUE THREAD

**Issue by AndrewLaganaro** [ChrisTitusTech/powershell-profile#6]
Hi Titus, I've tried to add Terminal icons to your script on my fork.

On **setup.ps1**, I added the line at the end

`Install-Module -Name Terminal-Icons -Repository PSGallery
`

On **Microsoft.PowerShell_profile.ps1**, I added 

`Import-Module -Name Terminal-Icons`

at the beggining, line 16.

I just want to ask if this is all I have to do to get those icons, I'm not used to code for powershell so I thought I'd be better to ask if it's just this that needs to be done in order for it to work.

Thanks!

**Comment by TheyCallMeZ** [comment]
open your powershell window, and type
notepad $PROFILE
paste your Import-Module line in here, save it and reload your powershell window / use chris's reload-profile command

**Comment by TheyCallMeZ** [comment]
@AndrewLaganaro  Did that resolve the issue for you? If not, what errors did you receive?

**Comment by TheyCallMeZ** [comment]
@AndrewLaganaro windows can be wonky with fonts from time to time. My two suggestions would be to reboot and see if the fonts are available or try installing them directly from [nerdfonts. ](https://www.nerdfonts.com/)

**Comment by ChrisTitusTech** [comment]
Ran into this on a machine and had to right click and install system-wide on the nerd fonts.
