### ISSUE TITLE
Fonts ZIP file missing in installation folder?

### ISSUE THREAD

**Issue by jcamp** [ChrisTitusTech/powershell-profile#63]
You mention in the notes that a zip file with fonts will be installed in the installation folder after setup?

Nothing in my folder after setting up? Is there another location that this is created?

**Comment by hamburgerghini1** [comment]
Yep, ran the script just now and didn't find it

**Comment by vitskr** [comment]
You don't need these fonts. All you need to do is go to Terminal Settings for your Powershell profile and change font to CaskaydiaCove Nerf Font Mono

**Comment by jcamp** [comment]
Yep did this anyway, just thought you should know... (watched your video ;) )
