### ISSUE TITLE
Fail on Test-Connection

### ISSUE THREAD

**Issue by KiimaRo** [ChrisTitusTech/powershell-profile#75]
Here's the whole error message I am getting. 

Test-Connection : A parameter cannot be found that matches parameter name 'TimeoutSeconds'.
At E:\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:5 char:66
+ ... GitHub = Test-Connection github.com -Count 1 -Quiet -TimeoutSeconds 1
+                                                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Test-Connection], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.TestConnectionCommand

**Comment by ShadowElixir** [comment]
Are you using powershell core or windows powershell?
If you're using windows powershell, update to powershell core.

**Comment by KiimaRo** [comment]
Ah, yeah, got it. But I am now getting this.
![image](https://github.com/ChrisTitusTech/powershell-profile/assets/92581749/7426b475-4696-4f3c-b15c-c27425496a8a)

And I've redownloaded the font and installed it again but nothing seems to be making it work.

**Comment by KiimaRo** [comment]
That was it, thank you.
