### ISSUE TITLE
Choco ?

### ISSUE THREAD

**Issue by geo-stanciu** [ChrisTitusTech/powershell-profile#8]
Hi Titus,

Why does this script need choco to be installed in order to work ?

**Comment by ChrisTitusTech** [comment]
Working on expanding this into Nodejs and a couple other installs that winget isn't doing properly.

There is a lot of manual work required to get a fully functional neovim in powershell working and why I added choco. Winget has been letting me down a bunch lately.

**Comment by geo-stanciu** [comment]
Thanks for the reply. Big fan. Anyway, I was sort of curious about it after running this on the company laptop and the security (debatable :) ) suite used flagged the script as trojan and I got asked several times by the security team what I wanted to do and why. Silly, nonsense, I know.

**Comment by ChrisTitusTech** [comment]
You can always just manually do the script without running it. Either downloading it as a ps1 file or just manually copy the raw profile into your own $PROFILE file. 
I get why it would trip security software as the trusted PSGallery and other powershell scripts can be malicious a lot of the time.
