### ISSUE TITLE
PowerShell has been updated. Please restart your shell to reflect changes

### ISSUE THREAD

**Issue by Schoggiweggli** [ChrisTitusTech/powershell-profile#82]
So PowerShell got updated from 7.4.2 to 7.4.3 and this message appears: 

PowerShell has been updated. Please restart your shell to reflect changes

but how ? reboot doesn't work.

**Comment by orjan-berg** [comment]
the profile uses winget as source for upgrade, and 7.4.3 isn't available in winget yet.

**Comment by Schoggiweggli** [comment]
Yeah it worked now, was too early.
