### ISSUE TITLE
Profile script cannot be loaded due to not being digitally signed.

### ISSUE THREAD

**Issue by Daggersoath** [ChrisTitusTech/powershell-profile#84]
After installation, launching a new instance of PowerShell results in an immediate error of the Microsoft.Powershell_profile.ps1 file being unable to be loaded due to it not being digitally signed.

`. : File C:\Users\Sora\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded. The file
C:\Users\Sora\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 is not digitally signed. You cannot run
this script on the current system. For more information about running scripts and setting execution policy, see
about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
+ . 'C:\Users\Sora\Documents\WindowsPowerShell\Microsoft.PowerShell_pro ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess`

Now tis can be resolved by self signing the profile, but this just results in another dependency complaining about not being signed.
My assumption is this is not the intended solution then given it is not described in the readme, which seems to imply just running the command `irm "https://github.com/ChrisTitusTech/powershell-profile/raw/main/setup.ps1" | iex` will have everything running smoothly.

Haven't seen any other issues in regards to signing issues so a little at a loss here.

Install was done from an elevated PowerShell instance and run in my user home folder (C:\Users\Sora)

**Comment by bitsper2nd** [comment]
You can change the powershell execution policy in the Windows 11 settings by clicking the button to turn it on.

![image](https://github.com/ChrisTitusTech/powershell-profile/assets/22452474/c97301a9-98a0-49e5-ad68-9e9d7435c563)

Or you can run this command in powershell:

`Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted`

**Comment by Daggersoath** [comment]
Yep that fixes it, thanks!
